title: "Hao Jiang"
baseurl: ""
url: ""

markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  publications:
    output: false
  news:
    output: false
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      navbar_name: Notes
